### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by Zruto** [weixinxu666/DA-DRN#2]
请问在和其他方法做对比实验时，你都把其他方法重新在LOL-real和LOL-synthetic这两个数据集上训练了一遍得到的结果吗？还是说用别人预训练好的模型？另外在LOL-synthetic上选取的900张作为训练集，100张作为验证集是随机选取的吗？

**Comment by weixinxu666** [comment]
kind、retinexnet是重新训练的，其他的是直接跑的，100张是lol数据集作者划分的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weixinxu666/DA-DRN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 下午3:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[weixinxu666/DA-DRN] 关于训练 (Issue #2)





 
请问在和其他方法做对比实验时，你都把其他方法重新在LOL-real和LOL-synthetic这两个数据集上训练了一遍得到的结果吗？还是说用别人预训练好的模型？另外在LOL-synthetic上选取的900张作为训练集，100张作为验证集是随机选取的吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zruto** [comment]
我刚又看了一下，LOL合成的1000张是放在一个文件夹里的，没有区分开呀

**Comment by weixinxu666** [comment]
在LOL&nbsp;v2中有区分了&nbsp; 你去看一下这篇文章：Sparse Gradient Regularized Deep Retinex Network for Robust Low-Light Image Enhancement，这篇文章拓展了LOL数据集，并发布了LOL v2版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weixinxu666/DA-DRN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weixinxu666/DA-DRN] 关于训练 (Issue #2)





 
我刚又看了一下，LOL合成的1000张是放在一个文件夹里的，没有区分开呀
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zruto** [comment]
好的，感谢

**Comment by Zruto** [comment]
你好，我看了这篇文章，但是没有在https://ieeexplore.ieee.org/document/9328179 里找到新的LOL数据集，你可以方便上传用于训练的900张和验证的100张合成数据集吗，或者贴一下原作者的下载地址

**Comment by weixinxu666** [comment]
数据集太大了&nbsp; 我不方便上传，地址我也难以找到了，我记得是在github找到的，你再找找呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weixinxu666/DA-DRN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weixinxu666/DA-DRN] 关于训练 (Issue #2)





 
你好，我看了这篇文章，但是没有在https://ieeexplore.ieee.org/document/9328179 里找到新的LOL数据集，你可以方便上传用于训练的900张和验证的100张合成数据集吗，或者贴一下原作者的下载地址
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zruto** [comment]
好的，我再确认一下，新的数据集不是这个吧https://github.com/weichen582/RetinexNet

**Comment by weixinxu666** [comment]
新的数据集&nbsp;real-world和&nbsp;synthetic都有1000张&nbsp; &nbsp;不是这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weixinxu666/DA-DRN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weixinxu666/DA-DRN] 关于训练 (Issue #2)





 
好的，我再确认一下，新的数据集不是这个吧https://github.com/weichen582/RetinexNet
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zruto** [comment]
嗯嗯，我再找找

**Comment by Zruto** [comment]
找到了 https://www.dropbox.com/s/1h4annqjkqcbuk6/LOL-v2.zip?dl=0
